apiVersion: v1
kind: Service
metadata:
  name: nsqd
  labels:
    name: "nsqd"
spec:
  clusterIP: 10.96.0.2
  selector:
    app: nsq
    component: nsqd
  ports:
  - port: 4150
    name: tcp
    targetPort: 4150
  - port: 4151
    name: http
    targetPort: 4151
