apiVersion: extensions/v1beta1
kind: DaemonSet 
metadata:
  name: nsqd
spec:
  template:
    metadata:
      labels:
        app: nsq
        component: nsqd
    spec:
      containers:
      - name: nsqd
        image: nsqio/nsq 
        imagePullPolicy: Always
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
               fieldPath: status.podIP
        resources:
          limits:
            cpu: 1000m
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 128Mi
        ports:
        - containerPort: 4150
          name: tcp
        - containerPort: 4151
          name: http
        livenessProbe:
          httpGet:
            path: /ping
            port: http
          initialDelaySeconds: 5
        readinessProbe:
          httpGet:
            path: /ping
            port: http
          initialDelaySeconds: 2
        volumeMounts:
        - name: data
          mountPath: /data
        command:
          - /bin/sh
          - -c
          - "nsqd --lookupd-tcp-address=10.96.0.3:4160 --broadcast-address=$POD_IP --data-path=/data "
      terminationGracePeriodSeconds: 5
      volumes:
      - name: data
        hostPath:
          path: /data/nsq
