apiVersion: v1
kind: Service
metadata:
  name: nsqlookupd
  labels:
    name: "nsqlookupd"
spec:
  clusterIP: 10.96.0.3
  selector:
    app: nsq
    component: nsqlookupd
  ports:
  - port: 4160
    name: tcp
    targetPort: 4160
  - port: 4161
    name: http
    targetPort: 4161
